# Link the C runtime statically so the binary runs on a clean Windows install
# without the Visual C++ redistributable (VCRUNTIME140.dll).
[target.'cfg(all(windows, target_env = "msvc"))']
rustflags = ["-C", "target-feature=+crt-static"]
